atletas:
    atletaID:
        description: ID do atleta
        type: int64
    clubeID:
        description: ID do clube do atleta
        type: int64
    apelido:
        description: Apelido do atleta
        type: string
    posicaoID:
        description: ID da posição do atleta
        type: int64
clubes:
    clubeID:
        description: ID do clube
        type: int64
    nome:
        description: Nome do clube
        type: string
    abreviacao:
        description: Abreviação do clube
        type: string
partidas:
    partidaID:
        description: UUID da partida
        type: string
    rodada:
        description: Rodada em que a partida ocorreu
        type: int64
    clubeMandanteID:
        description: ID do clube mandante
        type: int64
    clubeVisitanteID:
        description: ID do clube visitante
        type: int64
    mandantePlacar:
        description: Placar do clube mandante
        type: int64
    visitantePlacar:
        description: Placar do clube visitante
        type: int64
    resultado:
        description: Resultado final da partida ["Casa", "Visitante", "Empate"]
        type: string
    temporada:
        description: Temporada da partida
        type: int64
posicoes:
    posicaoID:
        description: ID da posição
        type: int64
    nome:
        description: Nome da posição
        type: string
    abreviacao:
        description: Abreviação da posição
        type: string
scouts:
    atletaID:
        description: ID do atleta
        type: int64
    partidaID:
        description: UUID do atleta
        type: string
    clubeID:
        description: ID do clube do atleta
        type: int64
    pontos:
        description: Pontuação do atleta nesta rodada
        type: float64
    pontosMedia:
        description: Média de pontos do atleta até está rodada (inclue rodada atual)
        type: float64
    preco:
        description: Preço do atleta nesta rodada
        type: float64
    precoVariacao:
        description: Variação do preço da rodada passada para está
        type: float64
    FS:
        description: Faltas sofridas
        type: float64
    PE:
        description: Passes errados
        type: float64
    A:
        description: Assistências
        type: float64
    FT:
        description: Finalizações na trave
        type: float64
    FD:
        description: Finalizações defendidas
        type: float64
    FF:
        description: Finalizações para fora
        type: float64
    G:
        description: Gols
        type: float64
    I:
        description: Impedimentos
        type: float64
    PP:
        description: Penaltis perdidos
        type: float64
    RB:
        description: Roubadas de bola
        type: float64
    FC:
        description: Faltas cometidas
        type: float64
    GC:
        description: Gols contras
        type: float64
    CA:
        description: Cartões Amarelos
        type: float64
    CV:
        description: Cartões Vermelhos
        type: float64
    SG:
        description: Jogo sem sofrer gols
        type: float64
    DD:
        description: Defesas dificeis
        type: float64
    DP:
        description: Defesa de penaltis
        type: float64
    GS:
        description: Gols sofridos
        type: float64
