version: '3.7'

x-airflow-environment: &airflow-environment
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_postgres:5432/airflow
    - AIRFLOW_CONN_HIVESERVER2_DEFAULT='hiveserver2://:@hive:10000'

services:
    airflow_webserver:
        build: airflow
        command: ./wait-for-it.sh airflow_postgres:5432 -t 60 -- bash ./scripts/start-webserver.sh
        depends_on:
            - airflow_postgres
        environment: *airflow-environment
        healthcheck:
            test: curl -f localhost:8080 || exit 1
        ports:
            - 8080:8080
        volumes:
            - ./airflow/dags:/opt/airflow/dags
            - ./airflow/data:/opt/airflow/data
            - ./airflow/include:/opt/airflow/include
            - ./config:/etc/hadoop

    airflow_scheduler:
        build: airflow
        command: ./wait-for-it.sh airflow_webserver:8080 -t 60 -- bash ./scripts/start-scheduler.sh
        depends_on:
            - airflow_webserver
        environment: *airflow-environment
        healthcheck:
            test: curl -f localhost:8793 || exit 1
        ports:
            - 8793:8793
        volumes:
            - ./airflow/dags:/opt/airflow/dags
            - ./airflow/data:/opt/airflow/data
            - ./airflow/include:/opt/airflow/include
            - ./config:/etc/hadoop

    airflow_postgres:
        image: postgres:13-alpine
        healthcheck:
            test: pg_isready -U postgres
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: airflow
            POSTGRES_DB: airflow

    hadoop:
        build: hadoop
        healthcheck:
            test: curl -f localhost:9870 || exit 1
        ports:
            - 9870:9870
            - 8020:8020
        volumes:
            - ./config:/etc/hadoop

    hadoop_datanode:
        build: hadoop
        command: hdfs datanode
        depends_on:
            - hadoop
        volumes:
            - ./config:/etc/hadoop

    hive:
        build: hive
        command: hive --service hiveserver2
        depends_on:
            - hive_postgresql
            - hive_metastore
            - hadoop_datanode
        ports:
            - 10000:10000
        volumes:
            - ./config:/etc/hive

    hive_metastore:
        build: hive
        command: ./start-metastore.sh
        depends_on:
            - hive_postgresql
            - hadoop_datanode
        ports:
            - 9083:9083
        volumes:
            - ./config:/etc/hive

    hive_postgresql:
        image: postgres:13-alpine
        healthcheck:
            test: pg_isready -U postgres
        environment:
            POSTGRES_USER: hive
            POSTGRES_PASSWORD: hive
            POSTGRES_DB: hive
