networks:
    default:
        name: cartolafc_network

services:
    broker:
        depends_on:
            - zookeeper
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
            - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
            - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
            - KAFKA_HEAP_OPTS=-Xms256m -Xmx256m
        image: confluentinc/cp-kafka:5.4.0

    datahub-frontend-react:
        depends_on:
            - datahub-gms
        environment:
            - DATAHUB_GMS_HOST=datahub-gms
            - DATAHUB_GMS_PORT=8080
            - DATAHUB_SECRET=YouKnowNothing
            - DATAHUB_APP_VERSION=1.0
            - DATAHUB_PLAY_MEM_BUFFER_SIZE=10MB
            - JAVA_OPTS=-Xms256m -Xmx256m -Dhttp.port=9002 -Dconfig.file=datahub-frontend/conf/application.conf
              -Djava.security.auth.login.config=datahub-frontend/conf/jaas.conf -Dlogback.configurationFile=datahub-frontend/conf/logback.xml
              -Dlogback.debug=false -Dpidfile.path=/dev/null
            - KAFKA_BOOTSTRAP_SERVER=broker:29092
            - DATAHUB_TRACKING_TOPIC=DataHubUsageEvent_v1
            - ELASTIC_CLIENT_HOST=elasticsearch
            - ELASTIC_CLIENT_PORT=9200
        image: linkedin/datahub-frontend-react:v0.8.6
        mem_limit: 512m
        ports:
            - 9002:9002

    datahub-gms:
        depends_on:
            - mysql
        environment:
            - DATASET_ENABLE_SCSI=false
            - EBEAN_DATASOURCE_USERNAME=datahub
            - EBEAN_DATASOURCE_PASSWORD=datahub
            - EBEAN_DATASOURCE_HOST=mysql:3306
            - EBEAN_DATASOURCE_URL=jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8
            - EBEAN_DATASOURCE_DRIVER=com.mysql.jdbc.Driver
            - KAFKA_BOOTSTRAP_SERVER=broker:29092
            - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry:8081
            - ELASTICSEARCH_HOST=elasticsearch
            - ELASTICSEARCH_PORT=9200
            - GRAPH_SERVICE_IMPL=elasticsearch
            - JAVA_OPTS=-Xms256m -Xmx256m
            - MAE_CONSUMER_ENABLED=true
            - MCE_CONSUMER_ENABLED=true
        image: linkedin/datahub-gms:v0.8.6
        mem_limit: 512m

    elasticsearch:
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - ES_JAVA_OPTS=-Xms256m -Xmx256m
        healthcheck:
            retries: 4
            start_period: 2m
            test:
                - CMD-SHELL
                - curl -sS --fail 'http://localhost:9200/_cluster/health?wait_for_status=yellow&timeout=0s' || exit 1
        image: elasticsearch:7.9.3
        mem_limit: 1g

    elasticsearch-setup:
        depends_on:
            - elasticsearch
        environment:
            - ELASTICSEARCH_HOST=elasticsearch
            - ELASTICSEARCH_PORT=9200
            - ELASTICSEARCH_PROTOCOL=http
        image: linkedin/datahub-elasticsearch-setup:v0.8.6

    kafka-setup:
        depends_on:
            - broker
            - schema-registry
        environment:
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_BOOTSTRAP_SERVER=broker:29092
        image: linkedin/datahub-kafka-setup:v0.8.6

    mysql:
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            - MYSQL_DATABASE=datahub
            - MYSQL_USER=datahub
            - MYSQL_PASSWORD=datahub
            - MYSQL_ROOT_PASSWORD=datahub
        image: mysql:5.7
        volumes:
            - ./datahub/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

    mysql-setup:
        depends_on:
            - mysql
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_PORT=3306
            - MYSQL_USERNAME=datahub
            - MYSQL_PASSWORD=datahub
            - DATAHUB_DB_NAME=datahub
        image: acryldata/datahub-mysql-setup:v0.8.6

    schema-registry:
        depends_on:
            - zookeeper
            - broker
        environment:
            - SCHEMA_REGISTRY_HOST_NAME=schemaregistry
            - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
        image: confluentinc/cp-schema-registry:5.4.0

    zookeeper:
        environment:
            - ZOOKEEPER_CLIENT_PORT=2181
            - ZOOKEEPER_TICK_TIME=2000
        image: confluentinc/cp-zookeeper:5.4.0

version: '3.8'
