version: '3.7'

x-airflow-environment: &airflow-environment
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_postgres:5432/airflow
    - AIRFLOW_CONN_HIVE_CLI_DEFAULT='hive-cli://:@hive:10000'

services:
    airflow_webserver:
        build: airflow
        command: ./wait-for-it.sh airflow_postgres:5432 -t 60 -- bash ./scripts/start-webserver.sh
        depends_on:
            - airflow_postgres
        environment: *airflow-environment
        healthcheck:
            test: curl -f localhost:8080 || exit 1
            timeout: 90s
        ports:
            - 8080:8080
        volumes:
            - ./airflow/dags:/opt/airflow/dags
            - ./airflow/data:/opt/airflow/data
            - ./airflow/include:/opt/airflow/include
            - ./config:/etc/hadoop

    airflow_scheduler:
        build: airflow
        command: ./wait-for-it.sh airflow_webserver:8080 -t 60 -- bash ./scripts/start-scheduler.sh
        depends_on:
            - airflow_webserver
        environment: *airflow-environment
        healthcheck:
            test: nc -z localhost 8793
            timeout: 90s
        volumes:
            - ./airflow/dags:/opt/airflow/dags
            - ./airflow/data:/opt/airflow/data
            - ./airflow/include:/opt/airflow/include
            - ./config:/etc/hadoop

    airflow_postgres:
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: airflow
            POSTGRES_DB: airflow
        healthcheck:
            test: pg_isready -U postgres
        image: postgres:13-alpine

    hadoop:
        build: hadoop
        healthcheck:
            test: wget --spider localhost:9870 || exit 1
            timeout: 90s
        ports:
            - 9870:9870
            - 8020:8020
        volumes:
            - ./config:/etc/hadoop

    hadoop_datanode:
        build: hadoop
        command: hdfs datanode
        healthcheck:
            test: wget --spider localhost:9864 || exit 1
            timeout: 90s
        depends_on:
            - hadoop
        volumes:
            - ./config:/etc/hadoop

    hive:
        build: hive
        command: hive --service hiveserver2
        depends_on:
            - hive_postgres
            - hive_metastore
            - hadoop_datanode
        healthcheck:
            test: nc -z localhost 10000
        ports:
            - 10000:10000
            - 10002:10002
        volumes:
            - ./config:/etc/hive

    hive_metastore:
        build: hive
        command: ./start-metastore.sh
        depends_on:
            - hive_postgres
            - hadoop_datanode
        healthcheck:
            test: nc -z localhost 9083
        volumes:
            - ./config:/etc/hive

    hive_postgres:
        environment:
            POSTGRES_USER: hive
            POSTGRES_PASSWORD: hive
            POSTGRES_DB: hive
        healthcheck:
            test: pg_isready -U postgres
        image: postgres:13-alpine

    superset:
        build: superset
        depends_on:
            - superset_postgres
            - hive
        environment:
            - SUPERSET_SQL_ALCHEMY=postgresql+psycopg2://superset:superset@superset_postgres:5432/superset
        healthcheck:
            test: curl --fail http://localhost:8088 || exit 1
        ports:
            - 8088:8088
        volumes:
            - ./config:/etc/hive
            - ./superset/dashboards:/opt/superset/dashboards

    superset_postgres:
        environment:
            POSTGRES_USER: superset
            POSTGRES_PASSWORD: superset
            POSTGRES_DB: superset
        healthcheck:
            test: pg_isready -U postgres
        image: postgres:13-alpine
