version: '3.7'
services:
    spark-worker:
        build:
            context: .
            dockerfile: Dockerfile
        command: start-slave.sh spark:7077
        depends_on:
            - spark
        environment:
            - SPARK_MASTER_URL=spark:7077

    spark:
        build:
            context: .
            dockerfile: Dockerfile
        command: start-master.sh
        ports:
            - 8000:8080

networks:
    default:
        external: true
        name: cartolafc
