version: '3.7'
services:
    hadoop:
        build: .
        ports:
            - 9870:9870
            - 8020:8020
    hadoop-datanode:
        build: .
        command: hdfs datanode
        depends_on:
            - hadoop
networks:
    default:
        external: true
        name: cartolafc
