version: '3.7'
services:
    hadoop:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            CLUSTER_NAME: "TRUE"
        env_file:
            - ./hadoop.env
        ports:
            - 9870:9870
            - 9000:9000
        volumes:
            - ./config:/etc/hadoop
            - ./dfs/name:/hadoop/dfs/name

    hadoop-datanode:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - hadoop
        env_file:
            - ./hadoop.env
        restart: always
        volumes:
            - ./config:/etc/hadoop
            - ./dfs/data:/hadoop/dfs/data

networks:
    default:
        external: true
        name: cartolafc
