version: '3.7'
services:
    hadoop:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 9870:9870
            - 8020:8020
        volumes:
            - ./config:/etc/hadoop
            - ./dfs/name:/hadoop/dfs/name

    hadoop-datanode:
        build:
            context: .
            dockerfile: Dockerfile
        command: hdfs datanode
        depends_on:
            - hadoop
        volumes:
            - ./config:/etc/hadoop
            - ./dfs/data:/hadoop/dfs/data

networks:
    default:
        external: true
        name: cartolafc
