version: '3.7'
services:
    hadoop:
        build: .
        ports:
            - 9870:9870
            - 8020:8020
        volumes:
            - ./config:/etc/hadoop

    hadoop-datanode:
        build: .
        command: hdfs datanode
        depends_on:
            - hadoop
        volumes:
            - ./config:/etc/hadoop

networks:
    default:
        external: true
        name: cartolafc
