version: '3.7'

x-airflow-environment: &airflow-environment
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow

services:
    airflow-webserver:
        build: .
        command: ./wait-for-it.sh airflow-postgres:5432 -t 60 -- bash ./scripts/start-webserver.sh
        depends_on:
            - airflow-postgres
        environment: *airflow-environment
        ports:
            - 8080:8080
        volumes:
            - ./dags:/opt/airflow/dags
            - ./data:/opt/airflow/data
            - ./include:/opt/airflow/include

    airflow-scheduler:
        build: .
        command: ./wait-for-it.sh airflow-webserver:8080 -t 60 -- bash ./scripts/start-scheduler.sh
        depends_on:
            - airflow-webserver
        environment: *airflow-environment
        ports:
            - 8793:8793
        volumes:
            - ./dags:/opt/airflow/dags
            - ./data:/opt/airflow/data
            - ./include:/opt/airflow/include

    airflow-postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: airflow
            POSTGRES_DB: airflow

networks:
    default:
        external: true
        name: cartolafc
